live_config_reload = true

import = [
    "~/.config/alacritty/themes/gruvbox-dark.toml",
]

[window]
padding = {x = 5, y = 5}
opacity = 0.8
decorations = 'none'

[scrolling]
history = 10000
multiplier = 3

[font]
normal.family = 'WenQuanYi Micro Hei Mono'
normal.style = 'Regular'
size = 14

[selection]
save_to_clipboard = true

[shell]
program = '/bin/zsh'

